# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Source\MimiProjects\part1\stdPyQt\naverApiSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.resize(640, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmMain.sizePolicy().hasHeightForWidth())
        frmMain.setSizePolicy(sizePolicy)
        frmMain.setMinimumSize(QtCore.QSize(640, 400))
        frmMain.setMaximumSize(QtCore.QSize(640, 400))
        font = QtGui.QFont()
        font.setFamily("한컴 말랑말랑 Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        frmMain.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(frmMain)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 621, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.searchLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.searchLayout.setContentsMargins(0, 0, 0, 0)
        self.searchLayout.setObjectName("searchLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 28, 44, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.txtSearch = QtWidgets.QLineEdit(self.groupBox)
        self.txtSearch.setEnabled(True)
        self.txtSearch.setGeometry(QtCore.QRect(93, 28, 401, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(49, 153, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 153, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.txtSearch.setPalette(palette)
        self.txtSearch.setObjectName("txtSearch")
        self.btnSearch = QtWidgets.QPushButton(self.groupBox)
        self.btnSearch.setGeometry(QtCore.QRect(500, 28, 75, 29))
        self.btnSearch.setObjectName("btnSearch")
        self.label.raise_()
        self.txtSearch.raise_()
        self.btnSearch.raise_()
        self.searchLayout.addWidget(self.groupBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(frmMain)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 621, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.resultLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.resultLayout_2.setContentsMargins(0, 0, 0, 0)
        self.resultLayout_2.setObjectName("resultLayout_2")
        self.lsvResult = QtWidgets.QListView(self.verticalLayoutWidget_2)
        self.lsvResult.setObjectName("lsvResult")
        self.resultLayout_2.addWidget(self.lsvResult)

        self.retranslateUi(frmMain)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        _translate = QtCore.QCoreApplication.translate
        frmMain.setWindowTitle(_translate("frmMain", "네이버 API 뉴스검색앱"))
        self.groupBox.setTitle(_translate("frmMain", "뉴스 검색"))
        self.label.setText(_translate("frmMain", "검색어"))
        self.btnSearch.setText(_translate("frmMain", "검색"))
